### ISSUE TITLE
cant see any props file in the current nuget

### ISSUE THREAD

**Issue by SimonCropp** [dittodhole/dotnet-SemVer.Stamp#23]
https://github.com/dittodhole/dotnet-SemVer.Stamp/blob/master/SemVer.Git.MSBuild.nupkg/Package.nuspec#L20

**Comment by dittodhole** [comment]
I just downloaded the raw [.nupkg-file](https://www.nuget.org/api/v2/package/SemVer.Git.MSBuild/1.1.0) and opened it with [NuGet Package Explorer](https://github.com/NuGetPackageExplorer/NuGetPackageExplorer):

![image](https://cloud.githubusercontent.com/assets/429216/14910498/3a1080ce-0dee-11e6-989d-3364e22f73e3.png)

I also verified the existance of the .props-file by creating a demo project and adding [SemVer.Git.MSBuild](https://www.nuget.org/packages/SemVer.Git.MSBuild/) to the project - I can verify that *SemVer.MSBuild.props* gets added to the root of the project.

Can you please elaborate?

**Comment by dittodhole** [comment]
This issue has no reproducible steps (and no meaningful problem description). Please re-open this issue if it still occurs, with a set of reproducible steps.
