### ISSUE TITLE
Uncommitted changes - Switch to ignore

### ISSUE THREAD

**Issue by DeadlyEmbrace** [dittodhole/dotnet-SemVer.Stamp#27]
Would it be possible to add a switch to ignore uncommitted changes? 
I have a project where temporary files are generated during the build which cause SemVer.Stamp to fail the build because there are uncommitted changes, however these changes are required for the project to build

**Comment by dittodhole** [comment]
As a workaround: Why not ignore those files from versioning?
This should make the Dirty-check succeed :)

**Comment by dittodhole** [comment]
This issue will be addressed with the upcoming release (2.0.0): Uncommitted changes are generally ignored, and do not break the stamping.
Thanks for your patience!

Best
Andreas
